#TRY AND EXCEPT
try:
    a>3
    print(a)
except:
    print('Something went wrong')
finally:
    print('The try except block is finished')

#AWAIT AND ASYNC
